export enum muscleGroupEnum {
	CHEST = 'Bröst',
	UPPER_CHEST = 'Övre bröst',
	BACK = 'Rygg',
	SHOULDERS = 'Axlar',
	FRONT_DELTS = 'Framsida axlar',
	SIDE_DELTS = 'Sida axlar',
	REAR_DELTS = 'Baksida axlar',
	UPPER_BACK = 'Övre rygg',
	LOWER_BACK = 'Ländrygg',
	TRAPS = 'Traps',
	LATS = 'Lats',
	LEGS = 'Ben',
	QUADS = 'Framsida lår',
	HAMSTRINGS = 'Hamstrings',
	GLUTES = 'Glutes',
	ADDUCTORS = 'Adduktorer',
	CALVES = 'Vader',
	ABS = 'Abs',
	ARMS = 'Armar',
	BICEPS = 'Biceps',
	TRICEPS = 'Triceps',
}
